# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: apt
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y --no-install-recommends \
          git-core \
          ca-certificates \
          wget
        
      # Runs a set of commands using the runners shell
      - name: clone
        run: git clone https://github.com/qnap-dev/QDK.git
        
              
      # Runs a set of commands using the runners shell
      - name: qdk
        run: cd QDK && sudo ./InstallToUbuntu.sh install
        
      # Runs a set of commands using the runners shell
      - name: export
        run: export PATH="/usr/share/QDK/bin:${PATH}"
    
      - name: mkdir
        run: mkdir alist-qkpg & cd alist-qkpg

      # Runs a set of commands using the runners shell
      - name: wget
        run: wget https://github.com/iranee/qnap-alist-webdav/releases/download/v3.9.2/alist_3.9.2_arm-x41.qpkg
        
      # Runs a set of commands using the runners shell
      - name: extract
        run: /usr/share/QDK/bin/qbuild --extract alist_3.9.2_arm-x41.qpkg | grep -v ./$ | xargs -I {} cat {}
                
      # Runs a set of commands using the runners shell
      - name: ls
        run: ls -lrt
      
      - name: mkdir
        run: cd ../ & mkdir tr-qkpg & cd tr-qkpg

      # Runs a set of commands using the runners shell
      - name: wget
        run: wget https://www.myqnap.org/repo/MTransmission3_3.0.0.2205_arm_64.qpkg
        
      # Runs a set of commands using the runners shell
      - name: extract
        run: /usr/share/QDK/bin/qbuild --extract alist_3.9.2_arm-x41.qpkg | grep -v ./$ | xargs -I {} cat {}
                
      # Runs a set of commands using the runners shell
      - name: ls
        run: ls -lrt
