# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: apt
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y --no-install-recommends \
          git-core \
          ca-certificates
      
      # Runs a set of commands using the runners shell
      - name: clone
        run: git clone https://github.com/qnap-dev/QDK.git
        
              
      # Runs a set of commands using the runners shell
      - name: qdk
        run: cd QDK && sudo ./InstallToUbuntu.sh install
        
      # Runs a set of commands using the runners shell
      - name: export
        run: export PATH="/usr/share/QDK/bin:${PATH}"
        
      # Runs a set of commands using the runners shell
      - name: ls
        run: ls -lrt
